# Generated by Django 4.0.2 on 2022-03-06 01:15

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_text', models.CharField(max_length=200)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to=polls.models.get_upload_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('year_published', models.CharField(max_length=5)),
                ('genre', models.CharField(max_length=100)),
                ('ROM', models.FileField(upload_to=polls.models.get_upload_file_name)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='challenges',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.game'),
        ),
    ]
