# Generated by Django 4.0.2 on 2022-03-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_game_console'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tagblob',
            field=models.TextField(default='None', max_length=400),
        ),
    ]
