# Generated by Django 4.0.2 on 2022-03-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_game_tagblob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='challenge_text',
        ),
        migrations.AddField(
            model_name='challenges',
            name='challenge_description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='challenges',
            name='challenge_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
