# Generated by Django 4.0.2 on 2022-03-06 09:45

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_challenges_challenge_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=polls.models.get_upload_file_name),
        ),
    ]
