# Generated by Django 4.0.2 on 2022-03-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_challenges_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Challenges',
            new_name='Challenge',
        ),
    ]
