# Generated by Django 4.0.2 on 2022-03-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_challenge_game_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='commentblob',
            field=models.TextField(default="Automod; 'Remember, no hate '", max_length=400),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='game_sub_id',
            field=models.IntegerField(default=1),
        ),
    ]
