# Generated by Django 4.0.2 on 2022-03-13 07:02

from django.db import migrations, models
import django.utils.timezone
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_challenge_commentblob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ROM',
            field=models.FileField(null=True, upload_to=polls.models.get_upload_file_name),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
