# Generated by Django 4.0.2 on 2022-03-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_challenge_duration_alter_game_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('commentblob', models.TextField(max_length=500)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.challenge')),
            ],
        ),
    ]
