# Generated by Django 4.0.2 on 2022-03-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tripcode',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
