# Generated by Django 3.2.5 on 2022-03-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_game_franchise_alter_game_rom'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
