# Generated by Django 4.0.2 on 2022-03-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_challenge_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='game_sub_id',
            field=models.IntegerField(default=0),
        ),
    ]
