# Generated by Django 4.0.2 on 2022-03-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_challenge_commentblob_alter_challenge_game_sub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='commentblob',
            field=models.TextField(default="Automod; 'Remember, no hate '\n Automod: 'Remember, be on-topic' ", max_length=400),
        ),
    ]
